"""
Django settings for relance_patient project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.urls import reverse
from pathlib import Path
from dotenv import load_dotenv, find_dotenv

#load environment variables
#env_path = Path('C:/Users/HP ProBook/Documents/farrel')/'.env'
load_dotenv(find_dotenv())


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'at7l&9=3s_m)(l$c2h$xh6-871vsc6x^7%@g_b+ft%!(31y&o4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'authentication.apps.AuthenticationConfig',
    'patientlisting.apps.PatientlistingConfig',
    'dashboard.apps.DashboardConfig',
    'activite_relance.apps.ActiviteRelanceConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mytrack.apps.MytrackConfig',
    'reversion',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'global_login_required.GlobalLoginRequiredMiddleware',
    'dashboard.middleware.IsCC',
    'dashboard.middleware.IsSuper',
]

ROOT_URLCONF = 'relance_patient.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processor.get_path_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'relance_patient.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bd_appointment',
        'USER': 'root',
        'PASSWORD':'password',
        'HOST':'127.0.0.1',
        'PORT': 3306,
    },

    # 'sigdep': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'openmrs',
    #     'USER': 'powerbi_readonly',
    #     'PASSWORD':'txsxFa4dnNCHu8WgDt',
    #     'HOST':'20.185.232.96',
    #     'PORT':'3306',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fr-Fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

#AUTHENTICATION MODEL
AUTH_USER_MODEL = 'authentication.Account'


# PUBLIC VIEW
PUBLIC_VIEWS = [
    'authentication.views.logout_view',
    'authentication.views.login_view',
]

PUBLIC_PATHS = [
    '^%s.*' % MEDIA_URL, # allow public access to any media on your application
    r'^/account/.*', # allow public access to all django-allauth views
]


# LOGIN STAFF URL REDIRECT
CC_LOGIN_URL = '/relance/list-relance/'
SUPER_LOGIN_URL = '/site-list/'
DASHBOARD_URL = '/'


# CONNEXION PARMS
AUTH_SIGDEP = (os.getenv('USER_NAME'),os.getenv('PASSWORD'))
DATA_URL = os.getenv('URL_API')
